repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        exclude: ^mkdocs.yml$
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/swiss-ai-center/mdwrap
    rev: 0.2.1
    hooks:
      - id: mdwrap
        args: [--print-width, "80", --fmt]
