repo_url: https://github.com/csia-pme/a-guide-to-mlops
repo_name: csia-pme/a-guide-to-mlops
site_name: A guide to MLOps
site_author: CSIA-PME contributors
site_url: https://csia-pme.github.io/a-guide-to-mlops/
site_description: >-
  A simple yet complete guide to MLOps tools and practices - from a conventional way to a modern approach of working with ML projects.
copyright: Copyright &copy; 2022 - 2023 CSIA-PME
nav:
  # - Home: index.md TODO: Discuss this entry
  - Introduction:
      - introduction.md
      - tools.md
  - Part 1 - Local training and model evaluation:
      - "Introduction": part-1-local-training-and-model-evaluation/introduction.md
      - "Chapter 1 - Run a simple ML experiment with Jupyter Notebook": part-1-local-training-and-model-evaluation/chapter-1-run-a-simple-ml-experiment-with-jupyter-notebook/index.md
      - "Chapter 2 - Adapt and move the Jupyter Notebook to Python scripts": part-1-local-training-and-model-evaluation/chapter-2-adapt-and-move-the-jupyter-notebook-to-python-scripts/index.md
      - "Chapter 3 - Initialize Git and DVC for local training": part-1-local-training-and-model-evaluation/chapter-3-initialize-git-and-dvc-for-local-training/index.md
      - "Chapter 4 - Reproduce the ML experiment with DVC": part-1-local-training-and-model-evaluation/chapter-4-reproduce-the-ml-experiment-with-dvc/index.md
      - "Chapter 5 - Track model evolution with DVC": part-1-local-training-and-model-evaluation/chapter-5-track-model-evolution-with-dvc/index.md
      - "Conclusion": part-1-local-training-and-model-evaluation/conclusion.md
  - Part 2 - Move to the cloud:
      - "Introduction": part-2-move-to-the-cloud/introduction.md
      - "Chapter 6 - Move the ML experiment data to the cloud": part-2-move-to-the-cloud/chapter-6-move-the-ml-experiment-data-to-the-cloud/index.md
      - "Chapter 7 - Move the ML experiment code to the cloud": part-2-move-to-the-cloud/chapter-7-move-the-ml-experiment-code-to-the-cloud/index.md
      - "Chapter 8 - Reproduce the ML experiment in a CI/CD pipeline": part-2-move-to-the-cloud/chapter-8-reproduce-the-ml-experiment-in-a-cicd-pipeline/index.md
      - "Chapter 9 - Track model evolution in the CI/CD pipeline with CML": part-2-move-to-the-cloud/chapter-9-track-model-evolution-in-the-cicd-pipeline-with-cml/index.md
      - "Conclusion": part-2-move-to-the-cloud/conclusion.md
  - Part 3 - Serve and deploy the model online:
      - "Introduction": part-3-serve-and-deploy-the-model-online/introduction.md
      - "Chapter 10 - Save and load the model with MLEM": part-3-serve-and-deploy-the-model-online/chapter-10-save-and-load-the-model-with-mlem/index.md
      - "Chapter 11 - Serve the model locally with MLEM": part-3-serve-and-deploy-the-model-online/chapter-11-serve-the-model-locally-with-mlem/index.md
      - "Chapter 12 - Deploy and access the model on Kubernetes with MLEM": part-3-serve-and-deploy-the-model-online/chapter-12-deploy-and-access-the-model-on-kubernetes-with-mlem/index.md
      - "Chapter 13 - Train the model on a Kubernetes pod with CML": part-3-serve-and-deploy-the-model-online/chapter-13-train-the-model-on-a-kubernetes-pod-with-cml/index.md
      - "Conclusion": part-3-serve-and-deploy-the-model-online/conclusion.md
  - Part 4 - Labeling the data and retrain:
      - "Introduction": part-4-labeling-the-data-and-retrain/introduction.md
      - "Chapter 14 - Setup Label Studio": part-4-labeling-the-data-and-retrain/chapter-14-setup-label-studio/index.md
      - "Chapter 15 - Import existing data to Label Studio": part-4-labeling-the-data-and-retrain/chapter-15-import-existing-data-to-label-studio/index.md
      - "Chapter 16 - Label new data with Label Studio": part-4-labeling-the-data-and-retrain/chapter-16-label-new-data-with-label-studio/index.md
      - "Chapter 17 - Retrain the model from new data with DVC Sync": part-4-labeling-the-data-and-retrain/chapter-17-retrain-the-model-from-new-data-with-dvc-sync/index.md
      - "Chapter 18 - Link the model to Label Studio and get predictions": part-4-labeling-the-data-and-retrain/chapter-18-link-the-model-to-label-studio-and-get-predictions/index.md
      - "Conclusion": part-4-labeling-the-data-and-retrain/conclusion.md
  - Conclusion: conclusion.md
edit_uri: blob/main/docs/
theme:
  language: en
  icon:
    logo: material/all-inclusive
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - minify:
      minify_html: true
  - search
  - social
  - tags
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
  - glightbox
extra:
  social:
    - icon: material/earth
      link: https://swiss-ai-center.ch
      name: Swiss AI Center
    - icon: material/github
      link: https://github.com/csia-pme/csia-pme
      name: CSIA-PME on GitHub
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - javascripts/tablesort.js
