repo_url: https://github.com/swiss-ai-center/a-guide-to-mlops
repo_name: swiss-ai-center/a-guide-to-mlops
site_name: A guide to MLOps
site_author: Swiss AI Center contributors
site_url: https://swiss-ai-center.github.io/a-guide-to-mlops/
site_description: >-
  A simple yet complete guide to MLOps tools and practices - from a conventional way to a modern approach of working with ML projects.
copyright: Copyright &copy; 2022 - 2023 Swiss AI Center
nav:
  - 🏁 Introduction:
      - "Syllabus": syllabus.md
      - "Concept": concept.md
      - "Tools": tools.md
  - 🏠 Local training and model evaluation:
      - part-1-local-training-and-model-evaluation/introduction.md
      - "Chapter 1 - Run a simple ML experiment with Jupyter Notebook": part-1-local-training-and-model-evaluation/chapter-1-run-a-simple-ml-experiment-with-jupyter-notebook.md
      - "Chapter 2 - Adapt and move the Jupyter Notebook to Python scripts": part-1-local-training-and-model-evaluation/chapter-2-adapt-and-move-the-jupyter-notebook-to-python-scripts.md
      - "Chapter 3 - Initialize Git and DVC for local training": part-1-local-training-and-model-evaluation/chapter-3-initialize-git-and-dvc-for-local-training.md
      - "Chapter 4 - Reproduce the ML experiment with DVC": part-1-local-training-and-model-evaluation/chapter-4-reproduce-the-ml-experiment-with-dvc.md
      - "Chapter 5 - Track model evolution with DVC": part-1-local-training-and-model-evaluation/chapter-5-track-model-evolution-with-dvc.md
      - "Conclusion": part-1-local-training-and-model-evaluation/conclusion.md
      - "Clean up": part-1-local-training-and-model-evaluation/clean-up.md
  - ☁️ Move the model to the cloud:
      - "Introduction": part-2-move-the-model-to-the-cloud/introduction.md
      - "Chapter 6 - Move the ML experiment code to the cloud": part-2-move-the-model-to-the-cloud/chapter-6-move-the-ml-experiment-code-to-the-cloud.md
      - "Chapter 7 - Move the ML experiment data to the cloud": part-2-move-the-model-to-the-cloud/chapter-7-move-the-ml-experiment-data-to-the-cloud.md
      - "Chapter 8 - Reproduce the ML experiment in a CI/CD pipeline": part-2-move-the-model-to-the-cloud/chapter-8-reproduce-the-ml-experiment-in-a-cicd-pipeline.md
      - "Chapter 9 - Track model evolution in the CI/CD pipeline with CML": part-2-move-the-model-to-the-cloud/chapter-9-track-model-evolution-in-the-cicd-pipeline-with-cml.md
      - "Chapter 10 - Work efficiently and collaboratively with Git": part-2-move-the-model-to-the-cloud/chapter-10-work-efficiently-and-collaboratively-with-git.md
      - "Conclusion": part-2-move-the-model-to-the-cloud/conclusion.md
      - "Clean up": part-2-move-the-model-to-the-cloud/clean-up.md
  - 🚚 Serve and deploy the model:
      - "Introduction": part-3-serve-and-deploy-the-model/introduction.md
      - "Chapter 11 - Save and load the model with MLEM": part-3-serve-and-deploy-the-model/chapter-11-save-and-load-the-model-with-mlem.md
      - "Chapter 12 - Serve the model locally with MLEM": part-3-serve-and-deploy-the-model/chapter-12-serve-the-model-locally-with-mlem.md
      - "Chapter 13 - Deploy and access the model on Kubernetes with MLEM": part-3-serve-and-deploy-the-model/chapter-13-deploy-and-access-the-model-on-kubernetes-with-mlem.md
      - "Chapter 14 - Continuous deployment of the model with MLEM and the CI/CD pipeline": part-3-serve-and-deploy-the-model/chapter-14-continuous-deployment-of-the-model-with-mlem-and-the-cicd-pipeline.md
      - "Chapter 15 - Train the model on a Kubernetes pod with CML": part-3-serve-and-deploy-the-model/chapter-15-train-the-model-on-a-kubernetes-pod-with-cml.md
      - "Conclusion": part-3-serve-and-deploy-the-model/conclusion.md
      - "Clean up": part-3-serve-and-deploy-the-model/clean-up.md
  - 🏷️ Labeling the data and retrain:
      - "Introduction": part-4-labeling-the-data-and-retrain/introduction.md
      - "Chapter 16 - Setup Label Studio": part-4-labeling-the-data-and-retrain/chapter-16-setup-label-studio.md
      - "Chapter 17 - Import existing data to Label Studio": part-4-labeling-the-data-and-retrain/chapter-17-import-existing-data-to-label-studio.md
      - "Chapter 18 - Label new data with Label Studio": part-4-labeling-the-data-and-retrain/chapter-18-label-new-data-with-label-studio.md
      - "Chapter 19 - Retrain the model from new data with DVC Sync": part-4-labeling-the-data-and-retrain/chapter-19-retrain-the-model-from-new-data-with-dvc-sync.md
      - "Chapter 20 - Link the model to Label Studio and get predictions": part-4-labeling-the-data-and-retrain/chapter-20-link-the-model-to-label-studio-and-get-predictions.md
      - "Conclusion": part-4-labeling-the-data-and-retrain/conclusion.md
      - "Clean up": part-4-labeling-the-data-and-retrain/clean-up.md
  - 🪄 Conclusion:
    - "Clean up": clean-up.md
    - "Conclusion": conclusion.md
edit_uri: blob/main/docs/
theme:
  language: en
  custom_dir: docs
  favicon: assets/images/favicon.svg
  icon:
    logo: material/all-inclusive
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - search
  - social
  - tags
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
  - glightbox
  - minify:
      minify_html: true
extra:
  social:
    - icon: material/earth
      link: https://swiss-ai-center.ch
      name: Swiss AI Center
    - icon: material/github
      link: https://github.com/swiss-ai-center
      name: Swiss AI Center on GitHub
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/mathjax.js
  - assets/javascripts/tablesort.js
  - assets/javascripts/parallax.js
  - assets/javascripts/scrollAnimations.js
