repo_url: https://github.com/swiss-ai-center/a-guide-to-mlops
repo_name: swiss-ai-center/a-guide-to-mlops
site_name: A guide to MLOps
site_author: Swiss AI Center contributors
site_url: https://mlops.swiss-ai-center.ch/
site_description: >-
  A simple yet complete guide to MLOps tools and practices - from a conventional way to a modern approach of working with ML projects.
copyright: Copyright &copy; 2022 - 2025 Swiss AI Center
nav:
  - 🏁 Introduction:
      - "Syllabus": syllabus.md
      - "Concept": concept.md
      - "Tools": tools.md
      - "References": references.md
      - "Cheatsheet": cheatsheet.md
  - 🏠 Local training and model evaluation:
      - "Introduction": part-1-local-training-and-model-evaluation/introduction.md
      - "Chapter 1.1 - Run a simple ML experiment with Jupyter Notebook": part-1-local-training-and-model-evaluation/chapter-11-run-a-simple-ml-experiment-with-jupyter-notebook.md
      - "Chapter 1.2 - Adapt and move the Jupyter Notebook to Python scripts": part-1-local-training-and-model-evaluation/chapter-12-adapt-and-move-the-jupyter-notebook-to-python-scripts.md
      - "Chapter 1.3 - Initialize Git and DVC for local training": part-1-local-training-and-model-evaluation/chapter-13-initialize-git-and-dvc-for-local-training.md
      - "Chapter 1.4 - Reproduce the ML experiment with DVC": part-1-local-training-and-model-evaluation/chapter-14-reproduce-the-ml-experiment-with-dvc.md
      - "Chapter 1.5 - Track model evolution with DVC": part-1-local-training-and-model-evaluation/chapter-15-track-model-evolution-with-dvc.md
      - "Conclusion": part-1-local-training-and-model-evaluation/conclusion.md
  - ☁️ Move the model to the cloud:
      - "Introduction": part-2-move-the-model-to-the-cloud/introduction.md
      - "Chapter 2.1 - Move the ML experiment code to the cloud": part-2-move-the-model-to-the-cloud/chapter-21-move-the-ml-experiment-code-to-the-cloud.md
      - "Chapter 2.2 - Move the ML experiment data to the cloud": part-2-move-the-model-to-the-cloud/chapter-22-move-the-ml-experiment-data-to-the-cloud.md
      - "Chapter 2.3 - Reproduce the ML experiment in a CI/CD pipeline": part-2-move-the-model-to-the-cloud/chapter-23-reproduce-the-ml-experiment-in-a-cicd-pipeline.md
      - "Chapter 2.4 - Track model evolution in the CI/CD pipeline with CML": part-2-move-the-model-to-the-cloud/chapter-24-track-model-evolution-in-the-cicd-pipeline-with-cml.md
      - "Chapter 2.5 - Work efficiently and collaboratively with Git": part-2-move-the-model-to-the-cloud/chapter-25-work-efficiently-and-collaboratively-with-git.md
      - "Conclusion": part-2-move-the-model-to-the-cloud/conclusion.md
  - 🚚 Serve and deploy the model:
      - "Introduction": part-3-serve-and-deploy-the-model/introduction.md
      - "Chapter 3.1 - Save and load the model with BentoML": part-3-serve-and-deploy-the-model/chapter-31-save-and-load-the-model-with-bentoml.md
      - "Chapter 3.2 - Serve the model locally with BentoML": part-3-serve-and-deploy-the-model/chapter-32-serve-the-model-locally-with-bentoml.md
      - "Chapter 3.3 - Build and publish the model with BentoML and Docker locally": part-3-serve-and-deploy-the-model/chapter-33-build-and-publish-the-model-with-bentoml-and-docker-locally.md
      - "Chapter 3.4 - Build and publish the model with BentoML and Docker with the CI/CD pipeline": part-3-serve-and-deploy-the-model/chapter-34-build-and-publish-the-model-with-bentoml-and-docker-with-the-cicd-pipeline.md
      - "Chapter 3.5 - Deploy and access the model on Kubernetes": part-3-serve-and-deploy-the-model/chapter-35-deploy-and-access-the-model-on-kubernetes.md
      - "Chapter 3.6 - Continuous deployment of the model with the CI/CD pipeline": part-3-serve-and-deploy-the-model/chapter-36-continuous-deployment-of-the-model-with-the-cicd-pipeline.md
      - "Chapter 3.7 - Use a self-hosted runner for the CI/CD pipeline": part-3-serve-and-deploy-the-model/chapter-37-use-a-self-hosted-runner-for-the-cicd-pipeline.md
      - "Chapter 3.8 - Train the model on a Kubernetes pod": part-3-serve-and-deploy-the-model/chapter-38-train-the-model-on-a-kubernetes-pod.md
      - "Conclusion": part-3-serve-and-deploy-the-model/conclusion.md
  - 🏷️ Labeling the data and retrain:
      - "Introduction": part-4-labeling-the-data-and-retrain/introduction.md
      - "Chapter 4.1 - Set up Label Studio": part-4-labeling-the-data-and-retrain/chapter-41-set-up-label-studio.md
      - "Chapter 4.2 - Label new data with Label Studio": part-4-labeling-the-data-and-retrain/chapter-42-label-new-data-with-label-studio.md
      - "Chapter 4.3 - Link the model to Label Studio": part-4-labeling-the-data-and-retrain/chapter-43-link-the-model-to-label-studio.md
      - "Chapter 4.4 - Retrain the model from new data with DVC": part-4-labeling-the-data-and-retrain/chapter-44-retrain-the-model-from-new-data-with-dvc.md
      - "Conclusion": part-4-labeling-the-data-and-retrain/conclusion.md
  - 🪄 Conclusion:
      - "Clean up": clean-up.md
      - "Conclusion": conclusion.md
edit_uri: blob/main/docs/
theme:
  language: en
  custom_dir: docs
  favicon: assets/images/favicon.svg
  icon:
    logo: material/all-inclusive
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - search
  - social
  - tags
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      fallback_to_build_date: true
  - glightbox
  - minify:
      minify_html: true
extra:
  social:
    - icon: material/earth
      link: https://swiss-ai-center.ch
      name: Swiss AI Center
    - icon: material/github
      link: https://github.com/swiss-ai-center
      name: Swiss AI Center on GitHub
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/mathjax.js
  - assets/javascripts/tablesort.js
  - assets/javascripts/parallax.js
  - assets/javascripts/scrollAnimations.js
