repo_url: https://github.com/csia-pme/a-guide-to-mlops
repo_name: csia-pme/a-guide-to-mlops
site_name: A guide to MLOps
site_author: CSIA-PME contributors
site_url: https://csia-pme.github.io/a-guide-to-mlops/
site_description: >-
  A simple yet complete guide to MLOps tools and practices - from a conventional way to a modern approach of working with ML projects.
copyright: Copyright &copy; 2022 - 2023 CSIA-PME
nav:
  - Home:
      - index.md
      - Get started: get-started/what-is-mlops/index.md
      - The guide: the-guide/introduction/index.md
  - Get started:
      - What is MLOps?: get-started/what-is-mlops/index.md
      - What problems is MLOps trying to solve?: get-started/what-problems-is-mlops-trying-to-solve/index.md
      - Why would MLOps be useful for me?: get-started/why-would-mlops-be-useful-for-me/index.md
      - The tools used in this guide: get-started/the-tools-used-in-this-guide/index.md
  - The guide:
      - Introduction: the-guide/introduction/index.md
      - "Chapter 1: Run a simple ML experiment": the-guide/chapter-1-run-a-simple-ml-experiment/index.md
      - "Chapter 2: Share your ML experiment code with Git": the-guide/chapter-2-share-your-ml-experiment-code-with-git/index.md
      - "Chapter 3: Share your ML experiment data with DVC": the-guide/chapter-3-share-your-ml-experiment-data-with-dvc/index.md
      - "Chapter 4: Reproduce the experiment with DVC": the-guide/chapter-4-reproduce-the-experiment-with-dvc/index.md
      - "Chapter 5: Track model evolutions with DVC": the-guide/chapter-5-track-model-evolutions-with-dvc/index.md
      - "Chapter 6: Orchestrate the workflow with a CI/CD pipeline": the-guide/chapter-6-orchestrate-the-workflow-with-a-cicd-pipeline/index.md
      - "Chapter 7: Track model evolutions in the CI/CD pipeline with CML": the-guide/chapter-7-track-model-evolutions-in-the-cicd-pipeline-with-cml/index.md
      - "Chapter 8: Serve the model with MLEM": the-guide/chapter-8-serve-the-model-with-mlem/index.md
      - Conclusion: the-guide/conclusion/index.md
  - Labelization:
      - Introduction: label-studio/introduction/index.md
      - Create a Label Studio project: label-studio/create-a-label-studio-project/index.md
      - Import existing data to Label Studio: label-studio/import-existing-data-to-label-studio/index.md
      - Annotate new data with Label Studio: label-studio/annotate-new-data-with-label-studio/index.md
      - Export data from Label Studio: label-studio/export-data-from-label-studio/index.md
  - Advanced concepts:
      - Convert the experiment data from the guide for Label Studio: advanced-concepts/convert-the-experiment-data-from-the-guide-for-label-studio/index.md
      - Deploy MinIO: advanced-concepts/deploy-minio/index.md
      - Deploy Label Studio: advanced-concepts/deploy-label-studio/index.md
      - Link your ML model with Label Studio: advanced-concepts/link-your-ml-model-with-label-studio/index.md
      - Train the model on a Kubernetes cluster with CML: advanced-concepts/train-the-model-on-a-kubernetes-cluster-with-cml/index.md
  - Known limitations:
      - "CML: Cannot create a runner every time": known-limitations/cml-cannot-create-a-runner-every-time/index.md
      - "CML: Cannot specify an affinity to run the pod on Kubernetes": known-limitations/cml-cannot-specify-an-affinity-to-run-the-pod-on-kubernetes/index.md
      - "DVC & Git: Data and code cannot evolve independently": known-limitations/dvc-git-data-and-code-cannot-evolve-independently/index.md
      - "Global: Missing elements in comparison to other user-friendly solutions": known-limitations/global-missing-elements-in-comparison-to-other-user-friendly-solutions/index.md
      - "Label Studio: Does the predictions made by our ML model really help the person annotating the dataset": known-limitations/label-studio-does-the-predictions-made-by-our-ml-model-really-help-the-person-annotating-the-dataset/index.md
      - "Label Studio: The export of the dataset is manual": known-limitations/label-studio-the-export-of-the-dataset-is-manual/index.md
      - "Label Studio: The retraining of the ML model is difficult": known-limitations/label-studio-the-retraining-of-the-ml-model-is-difficult/index.md
edit_uri: blob/main/docs/
theme:
  language: en
  icon:
    logo: material/all-inclusive
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - minify:
      minify_html: true
  - search
  - social
  - tags
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
  - glightbox
extra:
  social:
    - icon: material/earth
      link: https://swiss-ai-center.ch
      name: Swiss AI Center
    - icon: material/github
      link: https://github.com/csia-pme/csia-pme
      name: CSIA-PME on GitHub
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - javascripts/tablesort.js
