[tool.poetry]
name = "a-guide-to-mlops"
version = "0.1.0"
description = "CSIA-PME - A Guide to MLOps"
authors = []
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^2.0.2"
matplotlib = "^3.7.1"
scikit-learn = "^1.2.2"
seaborn = "^0.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
