[tool.poetry]
name = "guide-notebook"
version = "0.1.0"
description = "Jupyter Notebook for MLOps guide"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "guide_notebook"}]

[tool.poetry.dependencies]
python = "^3.8"
jupyterlab = "^4.0.1"
pandas = "^2.0.2"
matplotlib = "^3.7.1"
scikit-learn = "^1.2.2"
seaborn = "^0.12.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
