log:
  level: error

api: {}

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: ludovic.delafontaine@heig-vd.ch
      # https://acme-v02.api.letsencrypt.org/directory by default, use https://acme-staging-v02.api.letsencrypt.org/directory for testing
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme.json
