stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features/test.pkl
    - data/features/tfidf
    - data/features/train.pkl
    - data/features/vectorizer
  train:
    cmd: python src/train.py data/features models/rf
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - models/rf
  evaluate:
    cmd: python src/evaluate.py models/rf data/features
    deps:
    - models/rf
    - src/evaluate.py
    outs:
    - evaluation/plots/metrics:
        cache: false
    metrics:
    - evaluation/metrics.json:
        cache: false
    plots:
    - evaluation/plots/importance.png:
        cache: false
    - evaluation/plots/prc.json:
        cache: false
        x: recall
        y: precision
    - evaluation/plots/sklearn/confusion_matrix.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
    - evaluation/plots/sklearn/roc.json:
        cache: false
        x: fpr
        y: tpr
