networks:
  traefik:
    name: traefik
  minio:
    name: minio

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:${MINIO_IMAGE_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - minio.env
    environment:
      - MINIO_DOMAIN=${MINIO_API_FQDN}
      - MINIO_SERVER_URL=https://${MINIO_API_FQDN}
      - MINIO_BROWSER_REDIRECT_URL=https://${MINIO_CONSOLE_FQDN}
    command: server --address ":9000" --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - traefik
      - minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data:rw
    labels:
      # Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Console HTTP
      - traefik.http.routers.minio-console-http.rule=Host(`${MINIO_CONSOLE_FQDN}`)
      - traefik.http.routers.minio-console-http.entrypoints=web
      - traefik.http.routers.minio-console-http.middlewares=redirect-to-https
      - traefik.http.routers.minio-console-http.service=minio-console
      # API HTTP
      - traefik.http.routers.minio-api-http.rule=Host(`${MINIO_API_FQDN}`)
      - traefik.http.routers.minio-api-http.entrypoints=web
      - traefik.http.routers.minio-api-http.middlewares=redirect-to-https
      - traefik.http.routers.minio-api-http.service=minio-api
      # Console HTTPS
      - traefik.http.routers.minio-console-https.rule=Host(`${MINIO_CONSOLE_FQDN}`)
      - traefik.http.routers.minio-console-https.entrypoints=websecure
      - traefik.http.routers.minio-console-https.tls=true
      - traefik.http.routers.minio-console-https.tls.certresolver=letsencrypt
      - traefik.http.routers.minio-console-https.service=minio-console
      # API HTTPS
      - traefik.http.routers.minio-api-https.rule=Host(`${MINIO_API_FQDN}`)
      - traefik.http.routers.minio-api-https.entrypoints=websecure
      - traefik.http.routers.minio-api-https.tls=true
      - traefik.http.routers.minio-api-https.tls.certresolver=letsencrypt
      - traefik.http.routers.minio-api-https.service=minio-api
      # Console service
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      # API service
      - traefik.http.services.minio-api.loadbalancer.server.port=9000

  mc:
    container_name: mc
    image: minio/mc:${MC_IMAGE_VERSION:-latest}
    depends_on:
      - minio
    env_file:
      - minio.env
    networks:
      - minio
    entrypoint: >
      sh -c "
        mc config host rm local;
        mc config host add --api s3v4 local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
        mc mb --ignore-existing local/mlops-example;
      "
