name: MLOps The Guide

on:
  # Runs on pushes targeting main branch
  push:
    branches:
      - main
    paths:
      - .github/workflows/mlops-the-guide.yml
      - docs/part-1-local-training-and-model-evaluation
      - docs/part-2-move-the-model-to-the-cloud
      - docs/part-3-serve-and-deploy-the-model
      - docs/part-4-labeling-the-data-and-retrain
      - checkpoint_generator

  # Runs on pull requests
  pull_request:
    paths:
      - .github/workflows/mlops-the-guide.yml
      # TODO: add the paths to the parts

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry==1.4.0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Configure Git
        run: |
          # Note: we do not actually push any changes to the repository, this allows to commit locally
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Test by generating the chapters
        run: poetry run python3 checkpoint_generator/main.py --no-save
